processor-toolbox:

    processors:

        - type: egg-processor
          name: egg1
        - type: forward-fftw
          name: fft1
        - type: convert-to-power
          name: to-ps1

        - type: egg-processor
          name: egg2
        - type: forward-fftw
          name: fft2
        - type: convert-to-power
          name: to-ps2

        - type: data-accumulator
          name: acc
        - type: gain-variation
          name: gainvar

        - type: variable-spectrum-discriminator
          name: discrim
        - type: sequential-track-finder
          name: seq-tr-clust
        - type: overlapping-track-clustering
          name: otc
        - type: iterative-track-clustering
          name: itc
        - type: track-proc-ws
          name: tr-proc-ws
        - type: multi-peak-track-builder
          name: mptb
        - type: multi-peak-event-builder
          name: mpeb

        - type: apply-cut
          name: ac1a

        - type: apply-cut
          name: ac1b

        - type: apply-cut
          name: density-cut

        - type: apply-cut
          name: first-track-nup-cut

        - type: apply-cut
          name: event-time-cut

        - type: apply-cut
          name: npoints-cut

        - type: basic-root-writer
          name: brw
        - type: root-tree-writer
          name: trw
      #  - type: root-tree-writer
      #    name: trw2

    connections:

        # Header processing
        - signal: "egg1:header"
          slot: "fft1:header"

      #  -signal: "egg1:header"
      #   slot: "trw2: header"

        - signal: "egg1:ts"
          slot: "fft1:ts-fftw"

        # First egg processing
        - signal: "fft1:fft"
          slot: "to-ps1:fs-fftw-to-psd"

        - signal: "to-ps1:psd"
          slot: "acc:ps"

        - signal: "acc:ps-finished"
          slot: "gainvar:ps-var"

        - signal: "acc:ps-finished"
          slot: "brw:psd"                 # Write accumulated PSD histogram

        - signal: "gainvar:gain-var"
          slot: "brw:gain-var"            # Write gain-var histogram

        - signal: "gainvar:gain-var"
          slot: "discrim:gv"

        # Second egg processing
        - signal: "egg2:header"
          slot: "fft2:header"

        - signal: "egg2:ts"
          slot: "fft2:ts-fftw"

        - signal: "fft2:fft"
          slot: "to-ps2:fs-fftw-to-psd"

        - signal: "to-ps2:psd"
          slot: "discrim:ps-pre"

        - signal: "discrim:disc-1d"
          slot: "seq-tr-clust:disc-1d"

#        - signal: "discrim:disc-1d"
#          slot: "trw:disc-1d"             # Writing discriminated points to ROOT tree

        - signal: "seq-tr-clust:seq-cand"
          slot: "otc:seq-cand"

        - signal: "otc:seq-cand"
          slot: "itc:seq-cand"

        - signal: "itc:seq-cand"
          slot: density-cut:apply

        - signal: density-cut:pass
          slot: "ac1b:apply"

        - signal: "ac1b:pass"
          slot: "tr-proc-ws:seq-cand"

        - signal: "tr-proc-ws:track"
          slot: "mptb:track"

        - signal: "tr-proc-ws:track"
          slot: "trw:proc-track"          # Write processed tracks to a ROOT tree

        - signal: "egg2:egg-done"
          slot: "seq-tr-clust:done"

        - signal: "seq-tr-clust:clustering-done"
          slot: "otc:do-clustering"

        - signal: "otc:clustering-done"
          slot: "itc:do-clustering"

        - signal: "itc:clustering-done"
          slot: "mptb:do-clustering"

        - signal: "mptb:mpt"
          slot: "mpeb:mpt"

        - signal: "mptb:mpt-done"
          slot: "mpeb:do-clustering"

        - signal: "mpeb:event"
          slot: "first-track-nup-cut:apply"

        - signal: "first-track-nup-cut:pass"
          slot: "event-time-cut:apply"

        - signal: "event-time-cut:pass"
          slot: "npoints-cut:apply"

        - signal: "npoints-cut:pass"
          slot: "trw:mt-event"



    run-queue:
        - egg1
        - egg2


egg1:
    filename: "foo.egg"
    egg-reader: egg3
    number-of-slices: 0
    slice-size: 4096
    progress-report-interval: 10000

fft1:
    transform-flag: ESTIMATE

acc:
    number-to-average: 0
    signal-interval: 0

gainvar:
    normalize: false
    min-frequency: 0
    max-frequency: 100e6
    fit-points: 50

egg2:
    filename: "foo.egg"
    egg-reader: egg3
    number-of-slices: 0
    slice-size: 4096
    progress-report-interval: 10000

fft2:
    transform-flag: ESTIMATE

discrim:
    min-frequency: 5e6         # Here we chop the frequency range to (100 +/-
    max-frequency: 95e6        # 42.5) MHz, the active bandwidth of the RSA
    #snr-threshold-power: 6.0
    sigma-threshold: 5
    normalize: true
    neighborhood-radius: 2


seq-tr-clust:
    min-frequency: 5e6
    max-frequency: 95e6
    initial-slope : 350e6                # slope of a track with 1 point
    slope-method: weighted-first-point-ref
    n-slope-points: 10
    time-gap-tolerance: 0.2e-3
    frequency-acceptance: 56e3
    trimming-threshold: 7.5            # snr threshold for the first and last point of a candidate
    min-points: 5
    min-slope: 0

otc:
    max-track-width: 300e3          # For most tracks this only needs to be 150e3-ish. Only curved tracks profit from this number being bigger

itc:
    time-gap-tolerance: 2.0e-3
    frequency-acceptance: 300.0e3
    max-track-width: 100.0e3

tr-proc-ws:
    min-slope: 0

mptb:
    sideband-time-tol: 1e-3

mpeb:
    jump-time-tol: 3.0e-3

ac1a:
    seq-line-nup-cut:               # can be applied after stf, after otc or after itc
        min-total-nup: 0
        min-average-nup: 0
        time-or-bin-average: bin
        wide-or-narrow: wide        # wide is default

ac1b:
    seq-line-nup-cut:               # can be applied after stf, after otc or after itc
        min-total-nup: 10
        min-average-nup: 6.5
        time-or-bin-average: bin
        wide-or-narrow: wide        # wide is default

density-cut:
    seq-line-density-cut:
        min-density: 3e3


first-track-nup-cut:
    event-first-track-nup-cut:      # cut events if the summed or average nup is below threshold
        min-total-nup: 10
        min-average-nup: 7
        min-max-track-nup: 12.5
        wide-or-narrow: wide        # wide is default
        time-or-bin-average: bin

event-time-cut:
    event-time-in-acq-cut:
        min-time: 1e-3
        max-time: 5

npoints-cut:
    event-first-track-npoints-cut:
        min-points: 6
        n-tracks-in-event: 1         # cut is only applied if number of tracks in events is less or equal than this
brw:
    output-file: "GainVariation.root"
    file-flag: recreate

trw:
    output-file: "TracksAndEvents.root"
    file-flag: recreate
